# Assumes that conda, pip and build-essentials are installed
---
name: kompuke_gpu
channels:
- conda-forge

dependencies:
- python=3.7
- conda-build
- numpy
- matplotlib=3.3.3
- jupyter
- pandas
- nb_conda_kernels
- nbdime
- pycuda
- nvcc_linux-64
- ffmpeg

# Install environment:
# $ conda env create -f conda_environment.yml

# Activate environment:
# $ conda activate kompuke_gpu
